# Generated by Django 3.2.6 on 2021-12-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=False, max_length=50, null=False)),
                ('in_out', models.CharField(blank=True, max_length=2, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('leavetime', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attend',
                'managed': False,
            },
        ),
    ]
