# Generated by Django 3.2.6 on 2021-12-23 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_attend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
